version: '2.2'
services:
  config:
    build: ./config/
    healthcheck:
        test: curl -f http://localhost:8888/proxy/default && echo 'cool, it works'
        interval: 10s
        timeout: 10s
        retries: 5
    networks:
     - back
    ports:
     - "8888:8888"
  eureka:
    image: dthibau/dp-eureka
    networks:
     - back
    ports:
     - "1111:1111"
    depends_on: 
      config:
        condition: service_healthy
  livraison-service:
    image: dthibau/dp-livraison-service
    networks:
     - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  order-service:
    image: dthibau/dp-order-service
    networks:
     - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  order-query-service:
    image: dthibau/dp-order-query-service
    networks:
      - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  payment-service:
    image: dthibau/dp-payment-service
    networks:
      - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  product-service:
    image: dthibau/dp-product-service
    networks:
      - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  gateway:
    image: dthibau/dp-gateway
    networks:
      - back
    restart: always
    depends_on: 
      config:
        condition: service_healthy
    networks:
      - front
      - back
    ports:
      - 8080:8080
    restart: always
    depends_on: 
      config:
        condition: service_healthy
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    networks:
      - back
      
  redpanda:
    image : docker.redpanda.com/redpandadata/console:latest
    ports: 
      - 8079:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - back

  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:+ExitOnOutOfMemoryError
    networks:
      - back

networks:
  back:
  front:

volumes:
  kafka_data:
    driver: local
