eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
    healthcheck:
      enabled: true
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  level:
    root: INFO


spring:
  kafka:
    bootstrap-servers:
    - kafka:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer   
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer   
      properties:
        spring.json.trusted.packages: '*'
  datasource:
    url:
      'jdbc:h2:mem:testdb'
       
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1      
app:
  channel:
    order-saga: 'order-saga'
    ticket-command: 'ticket-command'
    payment-command: 'payment-command'
    payment-response: 'payment-response'
    order-event: 'order-event'
    ticket-event: 'ticket-event'
    delivery-event: 'delivery-event'
