spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer    
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer   
      properties:
        spring.json.trusted.packages: '*'
    bootstrap-servers:
    - kafka:9092
  datasource:
    url:
      'jdbc:h2:mem:testdb'
  jpa:
    show-sql: true

app:
  channel:
    order-status: 'order-status'
    ticket-status: 'ticket-status'
    payment-request: 'payment-request'
    payment-response: 'payment-response'
    delivery-status: 'delivery-status'
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
    healthcheck:
      enabled: true
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
    

management:
  endpoints:
    web:
      exposure:
        include: '*'
    
logging:
  level:
    root: INFO

