server:
  port: 8083

spring:
  jpa:
    show-sql: false

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer    
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer    
    
---
spring:
  config:
    activate:
      on-profile:
      - replica
      
server:
  port: 9083  
  
